### ISSUE TITLE
OLE error when trying to use RegEx search

### ISSUE THREAD

**Issue by rikaye** [VFPX/GoFish#231]
When attempting a project-based RegEx search I am getting the following error:

![image](https://github.com/VFPX/GoFish/assets/28717887/43c2247c-f2fe-4dc7-8910-4df76711b5eb)

For reference, this is the UI at the time i execute the search:

![image](https://github.com/VFPX/GoFish/assets/28717887/b37c9342-389b-4ae6-8f03-3cf388e026a5)

Checking the method that creates the RegEx object, it's first created from a VBScript class which would not have the ReturnFoxObjects property. It appears that if that object creation fails, it then attempts to create the RegEx object from Doug's SF_RegExp class which does have that property. I can think of several approaches to address this but thought I should raise this in case it's a problem with the current release of GoFish.

**Comment by rikaye** [comment]
FYI I pulled 7.0.32 from github and the same problem is present. Both regex and wildcard searches fail.

**Comment by rikaye** [comment]
Note that if I ignore the error, which occurs 2-3 times, the search with both regex or wildcards does complete successfully

**Comment by Jimrnelson** [comment]
Fixed in #233

Version 7.0.33 - 2024-05-25

- Add new item "Project in CurDir" to scope type dropdown (#232)
- Fixed RegEx bug (#231)

**Comment by rikaye** [comment]
Thanks, Jim. I’ll check that out when I’m back in the saddle on Tuesday.

rk

**Comment by rikaye** [comment]
Hi Jim,

Sadly this is still happening in 7.0.34. Seems to me like we have 2 different paths to RegEx (vbscript.dlll or SF_RegExp) and there are property refs in one which are not in the other. Please let me know if I can help or provide more info. I could take a fork and see what I come up with. 

![image](https://github.com/VFPX/GoFish/assets/28717887/cc30e907-0c7e-4d29-9609-3bf0eb44fd4e)

**Comment by rikaye** [comment]
One more side note, I had to recompile the app in the distro to get the debugger refs to appear.

**Comment by Jimrnelson** [comment]
> One more side note, I had to recompile the app in the distro to get the debugger refs to appear.

So, RK, that's pretty neat, since othersize code in PRGs is not visible in the debugger.  It's certainly an issue now that the GF search engine was converted from a VCX to a PRG (a few years ago).

Is there anything that you know of that I can do do the distributed app to achieve that effect?

**Comment by rikaye** [comment]
I just rebuilt the app with the recompile flag in the distro to get the debugger refs to appear.

**Comment by rikaye** [comment]
Next error is in this method:
  
```
Procedure EscapePattern()
		Lparameters;
			toRegExp,;
			tcPattern

		Return Icase(;
			Left(tcPattern, 1)  = "." , ".*\." + toRegExp.Escape_Like(Justext(m.tcPattern)),;
			Right(tcPattern, 1) = "." , toRegExp.Escape_Like(Juststem(m.tcPattern)) + "(?<!\..+)$",;
			"." $ m.tcPattern         , loRegExp.Escape_Like(Juststem(m.tcPattern)) + "\." + loRegExp.Escape_Like(Justext(m.tcPattern)),;
			EMPTY(tcPattern)          , "",;
			toRegExp.Escape_Like(m.tcPattern) + "\..*")

	Endproc

```
The assumption is the presence of the Escape_like method in the RegEx object. Guessing that it's in Doug's class but not the vbscript library.

**Comment by Jimrnelson** [comment]
> Hi Jim,
> 
> Sadly this is still happening in 7.0.34. Seems to me like we have 2 different paths to RegEx (vbscript.dlll or SF_RegExp) and there are property refs in one which are not in the other. Please let me know if I can help or provide more info. I could take a fork and see what I come up with.

Hey, RK --

Kind of embarrassing for me to release a "fix" that I did not test.

Apparently, you are using an infrequently used option to select a file template (or, maybe, others are trying to use it but not reporting the error that results).

In any case, I have some re-work to do there to avoid using SF_RegExp, as there can be conflicts.  I have yet to learn what procedure Escape_Like does.

**Comment by Jimrnelson** [comment]
> Guessing that it's in Doug's class but not the vbscript library.

Actually, that's not Doug's, it's Lutz Scheffler's.

I don't understand it other than to have learned that there may be conflicts if its used.

**Comment by rikaye** [comment]
Hence my editorial remark about not doing the work. :-) 

As mentioned in my last comment the presence of any file masking, not just *, will blow up in the current implementation. Sometimes it's faster to put in a simple mask to quickly override the other file extension settings. Having said that, I will just avoid that for now. 

On the dialog, it's my vague memory of more stuff being there and not so much blank space. So working as designed from the sound of it. :-)

**Comment by myearwood1** [comment]
From the beginning, I thought using grep itself would be better than the vbscript stuff. Check Project > Project info, Project Tab, Debug Info should be checked to show source code when the app crashes.

**Comment by Jimrnelson** [comment]
> From the beginning, I thought using grep itself would be better than the vbscript stuff. 

A little late to change horses now.  I believe the main issue is that vbscript is accessible within Fox as an object.  The vbscript object is used extensively throughout GF (certainly more places than I was ever aware of), so having it available as an object is critical.

**Comment by Jimrnelson** [comment]
> Check Project > Project info, Project Tab, Debug Info should be checked to show source code when the app crashes.

Yes, I have done than.  While it does show source code for VCXs and SCXs, it does not show source code for PRGs.

**Comment by Jimrnelson** [comment]
@rikaye 

So, another stab at fixing this:

Version 7.0.34 - 2024-05-29 (#236)

- Fixed bug (#231) related to file templates on "Advanced" screen (again).  Related changes:
    - You can enter multiple file templates, separated by commas.
    - If you do not enter a file extension, the "normal" list of file extensions (appearing on same screen) is used.
    - If you use '*' as the extension, GF may be bogged down searching files not of interest (such as text files created from binaries, or bak files).
- Bugs fixed:
    - Sorting on full path of file name.
    - Elapsed time was not including time to save results.

**Comment by myearwood1** [comment]
> > From the beginning, I thought using grep itself would be better than the vbscript stuff.
> 
> A little late to change horses now. I believe the main issue is that vbscript is accessible within Fox as an object. The vbscript object is used extensively throughout GF (certainly more places than I was ever aware of), so having it available as an object is critical.

It's software. It's very easy to change horses, as opposed to a recall of an automotive part. I've been doing a lot of removing vbscript and replacing things like the filescriptinghost object with windows api calls. I know you are launching grep, but you cannot user that to search inside a vcx memo field - another thing I think was done wrong from the start. We've already worked around all of that.

The user in this case could benefit greatly from your direct use of grep.

**Comment by rikaye** [comment]
Will check it out tomorrow and let you know.

Thanks!

rk

**Comment by rikaye** [comment]
Problem solved, Jim. Thanks!

**Comment by DougHennig** [comment]
@Jimrnelson I'm not sure I understand.

**Comment by myearwood1** [comment]
> Sorry for opening this can of worms, Jim. :-) I happen to have an asterisk in the file mask at the moment. Taking that out does bypass these errors so there's your use case for debugging. I can also confirm that having anything at all in the file mask will trigger the error.
> 
> ![image](https://private-user-images.githubusercontent.com/28717887/334438829-1fc56f91-5fa4-4b29-9a8e-ec1ae97ccac1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwODUzOTIsIm5iZiI6MTcxNzA4NTA5MiwicGF0aCI6Ii8yODcxNzg4Ny8zMzQ0Mzg4MjktMWZjNTZmOTEtNWZhNC00YjI5LTlhOGUtZWMxYWU5N2NjYWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDE2MDQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZTRmNGIyYjYzNDVkYTcxMjY4ZmQ0NDE5ZGVlYzAwY2I1OWU4Y2Y4NzZlMDEyMWFiNmZiZjhlMDhhZThjZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qsj4bJq0q82GwCwprhcI-4YJ7EHFyfIDFSG_L9d3xxM)
> 
> The advanced dialog is looking a bit wonky to me?.
> 
> My instinct would be to deprecate the vbscript dll path and just use the SF class for RegEx stsuff. But I'm not doing the work... :-)

@rikaye are you aware that there is a new feature I instigated to search text-only files with grep instead of the regex classes? In my application, using grep is 700 times faster than the existing regex stuff.

**Comment by Jimrnelson** [comment]
@rikaye @myearwood1 

I have been working on Mike's suggestion (#226) and hope to have a release as part of GF in the near future.  (Still some wrinkles to iron out).

I'm not sure where Mike is seeing an improvement of 700 times faster (when using regular expressions).  I am seeing results more like 4-6 times faster (which is still fantastic).

**Comment by myearwood1** [comment]
I am very thankful for your efforts in this @Jimrnelson 

I did also suggest how to speed up the regex stuff which you said was 7 times faster. Before that, I was experiencing 6000+ seconds to do a search that grep did on textfiles in 15 seconds. So together, you and I have made beyond fantastic improvements.

https://github.com/VFPX/GoFish/issues/226#issuecomment-2125536600

**Comment by myearwood1** [comment]
That shows 400 times faster. I did see one that was 700 times, but I don't have an image of it.

**Comment by Jimrnelson** [comment]
Not part of GF yet, a work in progress.  When implemented, you won’t have to do anything different other than to observe that GF works faster, in some cases many times faster. Sent from my iPhoneOn May 30, 2024, at 9:42 AM, Richard Kaye ***@***.***> wrote:﻿

@rikaye are you aware that there is a new feature I instigated to search text-only files with grep instead of the regex classes? In my application, using grep is 700 times faster than the existing regex stuff.

Hi Mike,
The original I bug I reported was related to how the file template was (not) getting properly parsed, not the search itself. Of course, faster is definitely better for the actual searching. :-)
Can you point me to where in GF is the feature to use grep that you mention?

**Comment by myearwood1** [comment]
I have almost 20,000 files to search through. This approach is not just a nice-to-have, but a critical thing for me. Thankfully Jim made a way that I could use Grep at least until he has his modifications ready.

**Comment by Jimrnelson** [comment]
I experienced an unbelievably long regret search once as well but could not reproduce it.  Subsequent runs had more reasonable results.  Of course changes since then, already implemented, have made use of regex friendly.  Sent from my iPhoneOn May 30, 2024, at 9:18 AM, Mike Yearwood ***@***.***> wrote:﻿
I am very thankful for your efforts in this @Jimrnelson
I did also suggest how to speed up the regex stuff which you said was 7 times faster. Before that, I was experiencing 6000+ seconds to do a search that grep did on textfiles in 15 seconds. So together, you and I have made beyond fantastic improvements.
#226 (comment)

**Comment by myearwood1** [comment]
I regularly experienced such slow searches. It's why I suggested grep instead - it has much less overhead.
